version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build_and_upload:
    docker:
      - image: cimg/openjdk:19.0
    steps:
      - checkout
      - run:
          name: Install Maven Dependencies
          command: mvn dependency:resolve
      - run:
          name: Run Maven Tests
          command: mvn test -Dnet.bytebuddy.experimental=true
      # Here, ensure you have a step that generates the coverage report, if it's not part of `mvn test`.
      - codecov/upload:
        # If needed, specify additional parameters for the codecov upload, like `file` or `flags`

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_upload:
          filters:
            branches:
              only: master
