version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0
    steps:
      - checkout
      - run:
          name: Install Maven Dependencies
          command: mvn dependency:resolve
      - run:
          name: Run Maven Tests
          command: mvn test -Dnet.bytebuddy.experimental=true

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  upload-to-codecov:
    jobs:
      - checkout 
      - codecov/upload
