version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Checkstyle Code Analysis
          command: mvn checkstyle:check

      - run:
          name: Run Unit Tests
          command: mvn test

      - run:
          name: Generate JaCoCo Coverage Report
          command: mvn jacoco:report
      - run:
          name: Upload Coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
