version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Checkstyle Code Analysis
          command: mvn checkstyle:check || true

      - run:
          name: Run Unit Tests
          command: mvn clean test

      - run:
          name: Generate JaCoCo Coverage Report
          command: mvn jacoco:report

      - run:
          name: List JaCoCo Report Before Upload
          command: |
            echo "Listing JaCoCo report directory:"
            ls -la target/site/jacoco/ || echo "JaCoCo report directory does not exist."

      - run:
          name: Upload Coverage to Codecov
          command: |
            echo "Uploading JaCoCo report to Codecov"
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f target/site/jacoco/jacoco.xml || echo "Codecov did not find the report"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
